spring:
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://sc.w0rm.cc:3306/tiamat?useUnicode=true&characterEncoding=UTF-8
      username: w0rm
      password: xuyang1001
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: wall,stat

      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false


host:
  server: https://sc.ftqq.com

appkey:
  server: SCU70956T0c15fbd0c9116e74a9e7e93fac9539ec5e0037cfebae0

appsecret:
  server:

